#!/usr/bin/env python3
"""Generate a complete HyperFrames index.html for QUICK mode - no hand-written HTML.

Quick mode = baked A-roll + opening push-in + crop changes on sentence boundaries + word-timed
captions. Everything is derived from timing-map.json (plan_cuts.py) and a small style file, so
every reel comes out the same quality and an agent (or a small local model) only has to supply
decisions: which words to highlight, where the face is.

Usage:
  build_reel.py --project edit --aroll assets/aroll.mp4 --timing-map timing-map.json \
                [--style style.json] [--highlights highlights.json] [--face 0.5,0.3] [--ltr]
  build_reel.py --selftest

style.json (all optional):
  {"font_file": "assets/SFArabic.ttf", "font_family": "SF Arabic", "caption_size": 68,
   "caption_top": 1236, "caption_color": "#fffdf7", "accent": "#c85218",
   "words_per_cue": 4, "push": 1.12, "states": [1.0, 1.08, 1.0, 1.14], "min_state_gap": 3.5,
   "band": 0.35}   # band = opacity of the dark band behind captions (0 to disable)
"""
import argparse
import html
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from plan_cuts import srt_cues  # noqa: E402

DEFAULT_STYLE = {
    "font_file": None, "font_family": "SF Arabic", "caption_size": 68, "caption_top": 1236,
    "caption_color": "#fffdf7", "accent": "#c85218", "words_per_cue": 4,
    "push": 1.12, "states": [1.0, 1.08, 1.0, 1.14], "min_state_gap": 3.5, "band": 0.35,
}
LATIN = re.compile(r"[A-Za-z]")
SENT_END = (".", "!", "?", "؟", "،", ",", "؛")


def tokens(text, highlights):
    """Cue text -> spans. Consecutive Latin words (and a number after them) become ONE ltr run,
    otherwise the RTL line orders them backwards ("Code Claude")."""
    out = []
    for w in text.split():
        latin = bool(LATIN.search(w)) or bool(out and out[-1]["lat"] and re.fullmatch(r"[\d.]+[.,]?", w))
        if latin and out and out[-1]["lat"]:
            out[-1]["w"] += " " + w
        else:
            out.append({"w": w, "lat": latin})
    marked = False
    for t in out:  # at most one highlight per cue
        bare = t["w"].strip(".,!?؟،؛")
        if not marked and (t["w"] in highlights or bare in highlights or any(h in t["w"].split() for h in highlights)):
            t["hl"] = marked = True
    return out


def crop_events(words, style, end):
    """Hard crop changes at sentence starts, cycling through `states`, never closer than
    min_state_gap seconds. The opening push owns the first seconds."""
    events, last, i = [], 0.0, 0
    states = style["states"]
    for prev, w in zip(words, words[1:]):
        t = w["out_start"]
        if prev["text"].rstrip().endswith(SENT_END) and t - last >= style["min_state_gap"] and t < end - 1:
            i += 1
            events.append((round(t, 3), states[i % len(states)]))
            last = t
    return events


def build_html(tm, aroll, style, highlights=(), face=(0.5, 0.3), rtl=True):
    s = {**DEFAULT_STYLE, **(style or {})}
    words = [w for w in tm["words"] if w["text"].strip()]
    end = tm["output_duration"]
    cues = []
    for a, b, text in srt_cues(words, max_words=s["words_per_cue"]):
        cues.append({"s": round(a, 3), "e": round(b, 3), "t": tokens(text, set(highlights))})
    for c, n in zip(cues, cues[1:]):
        c["e"] = min(c["e"] + 0.3, n["s"])          # read a beat longer, never overlap the next
    if cues:
        cues[-1]["e"] = end                          # last caption holds to the final frame
    crops = crop_events(words, s, end)
    fam = s["font_family"]
    font_face = (f'@font-face {{ font-family: "{fam}"; src: url("{s["font_file"]}"); font-weight: 100 900; }}'
                 if s["font_file"] else "")
    return f"""<!doctype html>
<html lang="{'ar' if rtl else 'en'}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1080, height=1920" />
    <!-- generated by reel-editor/scripts/build_reel.py (quick mode) — edit style.json, not this file -->
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      {font_face}
      * {{ margin: 0; padding: 0; box-sizing: border-box; }}
      html, body {{ width: 1080px; height: 1920px; overflow: hidden; background: #000; }}
      #root {{ position: relative; width: 100%; height: 100%; overflow: hidden; font-family: "{fam}", "Montserrat", sans-serif; }}
      #cam {{ position: absolute; inset: 0; overflow: hidden; }}
      #camInner {{ position: absolute; inset: 0; transform-origin: {face[0] * 100:.1f}% {face[1] * 100:.1f}%; }}
      #aroll {{ position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; }}
      /* soft band so light captions stay readable over bright walls (contrast audit) */
      #band {{ position: absolute; left: 0; right: 0; top: {s["caption_top"] - 70}px; height: 290px;
        background: linear-gradient(transparent, rgba(0, 0, 0, {s["band"]}) 35%, rgba(0, 0, 0, {s["band"]}) 65%, transparent); }}
      #caps {{ position: absolute; left: 80px; right: 80px; top: {s["caption_top"]}px; height: 150px; direction: {'rtl' if rtl else 'ltr'}; }}
      .cap {{ position: absolute; inset: 0; display: flex; justify-content: center; align-items: center; gap: 18px; opacity: 0;
        font-weight: 800; font-size: {s["caption_size"]}px; line-height: 1.1; color: {s["caption_color"]};
        text-shadow: 0 3px 18px rgba(0, 0, 0, 0.55), 0 1px 3px rgba(0, 0, 0, 0.6); }}
      .cap .lat {{ font-family: "Montserrat", "{fam}", sans-serif; direction: ltr; unicode-bidi: isolate; }}
      .cap .hl {{ color: #fffdf7; background: {s["accent"]}; padding: 0 18px 8px; border-radius: 16px; text-shadow: none; }}
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-duration="{end:.4f}" data-width="1080" data-height="1920">
      <div id="cam">
        <div id="camInner" data-layout-allow-overflow>
          <video id="aroll" class="clip" src="{html.escape(aroll)}" data-start="0" data-duration="{end:.4f}"
                 data-track-index="0" data-has-audio="true" playsinline></video>
        </div>
      </div>
      <div id="band"></div>
      <div id="caps"></div>
    </div>
    <script>
      const CUES = {json.dumps(cues, ensure_ascii=False)};
      const CROPS = {json.dumps(crops)};
      const tl = gsap.timeline({{ paused: true }});
      tl.set("#camInner", {{ scale: 1 }}, 0).to("#camInner", {{ scale: {s["push"]}, duration: 0.7, ease: "power4.out" }}, 0);
      CROPS.forEach(([t, k]) => tl.set("#camInner", {{ scale: k }}, t));
      const caps = document.getElementById("caps");
      CUES.forEach((c, i) => {{
        const d = document.createElement("div");
        d.className = "cap"; d.id = "cap" + i;
        c.t.forEach((t) => {{
          const sp = document.createElement("span");
          sp.textContent = t.w;
          if (t.lat) sp.classList.add("lat");
          if (t.hl) sp.classList.add("hl");
          d.appendChild(sp);
        }});
        caps.appendChild(d);
        tl.fromTo(d, {{ opacity: 0, y: 10 }}, {{ opacity: 1, y: 0, duration: 0.1, ease: "power2.out" }}, c.s).set(d, {{ opacity: 0 }}, c.e);
      }});
      window.__timelines = window.__timelines || {{}};
      window.__timelines["main"] = tl;
      tl.seek(0);
    </script>
  </body>
</html>
"""


def selftest():
    w = lambda t, a, b: {"text": t, "out_start": a, "out_end": b}
    tm = {"output_duration": 12.0, "words": [
        w("مرحبًا", 0.1, 0.5), w("يا", 0.5, 0.6), w("جماعة،", 0.6, 1.0),
        w("استخدام", 1.2, 1.6), w("Claude", 1.6, 1.9), w("Code", 1.9, 2.2), w("الآن.", 2.2, 2.6),
        w("Opus", 6.0, 6.4), w("5.5", 6.4, 6.8), w("أقوى.", 6.8, 7.4), w("شكرًا", 11.0, 11.6)]}
    page = build_html(tm, "assets/aroll.mp4", {}, highlights=["Claude", "شكرًا"])
    cues = json.loads(re.search(r"const CUES = (.*);", page).group(1))
    spans = [t["w"] for c in cues for t in c["t"]]
    assert "Claude Code" in spans and "Opus 5.5" in spans, spans          # Latin runs merged
    assert sum(1 for c in cues for t in c["t"] if t.get("hl")) == 2         # one highlight per cue max
    assert cues[-1]["e"] == 12.0                                             # last caption holds
    assert all(a["e"] <= b["s"] for a, b in zip(cues, cues[1:]))            # captions never overlap
    crops = json.loads(re.search(r"const CROPS = (.*);", page).group(1))
    assert crops and all(b[0] - a[0] >= 3.5 for a, b in zip(crops, crops[1:])), crops
    assert 'id="band"' in page and "rgba(0, 0, 0, 0.35)" in page
    assert 'data-has-audio="true"' in page and "@font-face" not in page
    assert "@font-face" in build_html(tm, "a.mp4", {"font_file": "assets/f.ttf"})
    print("build_reel selftest: OK")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--project", help="HyperFrames project dir (index.html is written here)")
    ap.add_argument("--aroll", default="assets/aroll.mp4", help="A-roll path relative to the project")
    ap.add_argument("--timing-map", help="timing-map.json from plan_cuts.py")
    ap.add_argument("--style", help="style.json (see docstring)")
    ap.add_argument("--highlights", help="JSON list of words to highlight (one per caption at most)")
    ap.add_argument("--face", default="0.5,0.3", help="face position as x,y fractions (zoom origin)")
    ap.add_argument("--ltr", action="store_true", help="left-to-right captions (default RTL)")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    if not (a.project and a.timing_map):
        ap.error("--project and --timing-map are required")
    tm = json.load(open(a.timing_map, encoding="utf-8"))
    style = json.load(open(a.style, encoding="utf-8")) if a.style else {}
    hl = json.load(open(a.highlights, encoding="utf-8")) if a.highlights else []
    face = tuple(float(v) for v in a.face.split(","))
    page = build_html(tm, a.aroll, style, hl, face, rtl=not a.ltr)
    open(os.path.join(a.project, "index.html"), "w", encoding="utf-8").write(page)
    cues = json.loads(re.search(r"const CUES = (.*);", page).group(1))
    print(f"index.html written: {tm['output_duration']:.2f}s, {len(cues)} captions -> {a.project}")


if __name__ == "__main__":
    main()
